trigger:
  - master
  - main
  - staging
  - alpha
  - azure-pipelines

parameters:
  - name: Deploy
    type: string
    values:
      - auto
      - true
      - false
    default: auto
  - name: Analyze
    type: string
    values:
      - disabled
      - auto
      - true
      - false
    default: disabled

pool:
  vmImage: 'ubuntu-latest' #'windows-2019'

resources:
  repositories:
    - repository: azure-pipelines-repo
      type: github
      name: hfrances/azure-pipelines-templates
      ref: refs/heads/${{
        iif(in(variables['Build.SourceBranchName'], 'master', 'staging', 'development', 'azure-pipelines', 'experimental'), 
          variables['Build.SourceBranchName'], 
          iif(eq(variables['Build.SourceBranchName'], 'main'), 
            'master', 
            'staging'
          )
        )}}
      endpoint: github-hfrances

extends:
  template: standard/azure-pipelines-template-libnet.yml@azure-pipelines-repo
  parameters:
    Deploy: ${{ parameters.Deploy }}
    Analyze: ${{ parameters.Analyze }}
    Test: auto
    Solution: '*.sln'
    ForceVersion: true
    SupportsNuget: true
