trigger:
  - master
  - main
  - staging
  - alpha
  - azure-pipelines

parameters:
  - name: Deploy
    type: string
    values:
      - auto
      - true
      - false
    default: auto
  - name: Analyze
    type: string
    values:
      - disabled
      - auto
      - true
      - false
    default: disabled

pool:
  vmImage: 'ubuntu-22.04' #'ubuntu-latest' or 'windows-2019'

resources:
  repositories:
    - repository: azure-pipelines-repo
      type: github
      name: hfrances/azure-devops-pipelines
      ref: refs/heads/azure-pipelines
      #ref: ${{
      #  iif(in(variables['Build.SourceBranchName'], 'master', 'staging', 'development', 'azure-pipelines', 'experimental'), 
      #    variables['Build.SourceBranch'], 
      #    iif(eq(variables['Build.SourceBranchName'], 'main'), 
      #      'refs/heads/master', 
      #      'refs/heads/staging'
      #    )
      #  )}}
      endpoint: github-hfrances

extends:
  template: standard/azure-pipelines-template-libnet.yml@azure-pipelines-repo
  parameters:
    Deploy: ${{ parameters.Deploy }}
    Analyze: ${{ parameters.Analyze }}
    Test: false
    Solution: '*.sln'
    ForceVersion: true
    SupportsNuget: true
