trigger:
  - master
  - main
  - staging
  - alpha
  - azure-pipelines

parameters:
  - name: Deploy
    type: string
    values:
      - auto
      - true
      - false
    default: auto
  - name: Analyze
    type: string
    values:
      - disabled
      - auto
      - true
      - false
    default: auto

pool:
  vmImage: 'ubuntu-22.04' #'ubuntu-latest' or 'windows-2019'

variables:
  repoRef: ${{
    iif(in(variables['Build.SourceBranchName'], 'master', 'staging', 'development', 'azure-pipelines', 'experimental'), 
      variables['Build.SourceBranch'], 
      iif(eq(variables['Build.SourceBranchName'], 'main'), 
        'refs/heads/master', 
        'refs/heads/staging'
      )
    )}}

jobs:
- job: DebugVariables
  displayName: 'Debug Variables'
  steps:
  - task: PowerShell@2
    displayName: 'Print Repository Reference'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Build.SourceBranch: $(Build.SourceBranch)"
        Write-Host "Build.SourceBranchName: $(Build.SourceBranchName)"
        Write-Host "repoRef: $(repoRef)"

